<?php
require __DIR__.'/../src/db.php';
$vehicles=$db->query("SELECT * FROM vehicles WHERE active=1 ORDER BY name")->fetchAll(PDO::FETCH_ASSOC);
$people=$db->query("SELECT * FROM personnel WHERE active=1 ORDER BY name")->fetchAll(PDO::FETCH_ASSOC);
$materials=$db->query("SELECT * FROM materials WHERE active=1 ORDER BY name")->fetchAll(PDO::FETCH_ASSOC);
$action=$_GET['action']??'home';
$editId=(int)($_GET['id']??0);

if($_SERVER['REQUEST_METHOD']==='POST'){
 $form=$_POST['form']??'';
 if($form==='person'){
  $id=(int)($_POST['id']??0);$name=trim($_POST['name']??'');$function=trim($_POST['function']??'');$vehicleId=(int)($_POST['vehicle_id']??0);
  if($name!==''){if($id>0){$s=$db->prepare('UPDATE personnel SET name=?,function=?,vehicle_id=? WHERE id=?');$s->execute([$name,$function,$vehicleId?:null,$id]);}else{$s=$db->prepare('INSERT INTO personnel(name,function,vehicle_id) VALUES(?,?,?)');$s->execute([$name,$function,$vehicleId?:null]);}}
  header('Location:?action=master');exit;
 }
 if($form==='vehicle'){
  $id=(int)($_POST['id']??0);$name=trim($_POST['name']??'');$call=trim($_POST['call_sign']??'');
  if($name!==''){if($id>0){$s=$db->prepare('UPDATE vehicles SET name=?,call_sign=? WHERE id=?');$s->execute([$name,$call,$id]);}else{$s=$db->prepare('INSERT INTO vehicles(name,call_sign) VALUES(?,?)');$s->execute([$name,$call]);}}
  header('Location:?action=master');exit;
 }
 if($form==='material'){
  $id=(int)($_POST['id']??0);$name=trim($_POST['name']??'');
  if($name!==''){if($id>0){$s=$db->prepare('UPDATE materials SET name=? WHERE id=?');$s->execute([$name,$id]);}else{$s=$db->prepare('INSERT INTO materials(name) VALUES(?)');$s->execute([$name]);}}
  header('Location:?action=master');exit;
 }
 if($form==='assign_person'){
  $personId=(int)($_POST['person_id']??0);$vehicleId=(int)($_POST['vehicle_id']??0);if($personId>0){$s=$db->prepare('UPDATE personnel SET vehicle_id=? WHERE id=?');$s->execute([$vehicleId?:null,$personId]);}header('Location:?action=master');exit;
 }
 if($form==='incident'){
  $incidentId=(int)($_POST['incident_id']??0);
  $data=[trim($_POST['incident_number']??''),trim($_POST['title']??''),trim($_POST['location']??''),$_POST['incident_date']??date('Y-m-d'),$_POST['start_time']??'',$_POST['end_time']??'',trim($_POST['material']??''),trim($_POST['notes']??''),trim($_POST['incident_leader']??''),trim($_POST['document_filled_by']??''),trim($_POST['culprit1_name']??''),$_POST['culprit1_birthdate']??'',trim($_POST['culprit2_name']??''),$_POST['culprit2_birthdate']??'',trim($_POST['culprit_unknown_name']??''),$_POST['culprit_unknown_birthdate']??''];
  if($incidentId>0){$s=$db->prepare('UPDATE incidents SET incident_number=?,title=?,location=?,incident_date=?,start_time=?,end_time=?,material=?,notes=?,incident_leader=?,document_filled_by=?,culprit1_name=?,culprit1_birthdate=?,culprit2_name=?,culprit2_birthdate=?,culprit_unknown_name=?,culprit_unknown_birthdate=? WHERE id=?');$s->execute([...$data,$incidentId]);$db->prepare('DELETE FROM incident_personnel WHERE incident_id=?')->execute([$incidentId]);$db->prepare('DELETE FROM incident_vehicles WHERE incident_id=?')->execute([$incidentId]);$db->prepare('DELETE FROM incident_materials WHERE incident_id=?')->execute([$incidentId]);$id=$incidentId;}
  else{$s=$db->prepare('INSERT INTO incidents(incident_number,title,location,incident_date,start_time,end_time,material,notes,incident_leader,document_filled_by,culprit1_name,culprit1_birthdate,culprit2_name,culprit2_birthdate,culprit_unknown_name,culprit_unknown_birthdate) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$s->execute($data);$id=(int)$db->lastInsertId();}
  $iv=$db->prepare('INSERT INTO incident_vehicles(incident_id,vehicle_id) VALUES(?,?)');$ip=$db->prepare('INSERT INTO incident_personnel(incident_id,vehicle_id,personnel_id) VALUES(?,?,?)');
  foreach($_POST['vehicles']??[] as $vid){$vid=(int)$vid;$iv->execute([$id,$vid]);foreach($_POST['crew'][$vid]??[] as $pid)$ip->execute([$id,$vid,(int)$pid]);}
  $im=$db->prepare('INSERT INTO incident_materials(incident_id,material_id) VALUES(?,?)');foreach($_POST['materials']??[] as $mid)$im->execute([$id,(int)$mid]);
  header('Location:?action=view&id='.$id);exit;
 }
}

function headerHtml(string $title='FW Verwaltung'):void{echo '<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.h($title).'</title><style>body{font-family:system-ui;margin:0;background:#f3f5f7;color:#18212b}header{background:#17212b;color:#fff;padding:18px 24px}nav a{color:#fff;margin-right:18px;text-decoration:none}main{max-width:1200px;margin:24px auto;padding:0 16px}.card{background:#fff;border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 2px 10px #0001}label{display:block;font-weight:600;margin:10px 0 5px}input,textarea,select{width:100%;box-sizing:border-box;padding:10px;border:1px solid #ccd3da;border-radius:8px}button,.btn{background:#d62828;color:#fff;border:0;border-radius:8px;padding:10px 16px;cursor:pointer;text-decoration:none;display:inline-block}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:16px}.muted{color:#667}.crew,.material-list,.person-block,.master-row{border:1px solid #ddd;border-radius:10px;padding:12px;margin:10px 0}.check{display:inline-block;margin:5px 12px 5px 0}.check input{width:auto}.danger{background:#eee;color:#222}.actions{display:flex;gap:10px;flex-wrap:wrap}.material-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:4px 16px}.material-list label{margin:5px 0;font-weight:500}.person-block h3{margin:0 0 8px}.master-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(330px,1fr));gap:18px}.vehicle-assignment{border:1px solid #ddd;border-radius:10px;padding:12px}.person-option{display:flex;align-items:center;gap:8px;margin:6px 0;padding:7px;border-radius:7px}.person-option input{width:auto}.person-option.disabled{opacity:.4;background:#f1f1f1}.inline{display:flex;gap:8px;align-items:end}.inline>*{flex:1}.small{font-size:.9rem}</style></head><body><header><strong>🚒 FW Verwaltung</strong><nav style="float:right"><a href="?">Einsätze</a><a href="?action=new">+ Neuer Einsatz</a><a href="?action=master">Stammdaten</a></nav></header><main>';}
function footerHtml():void{echo '</main></body></html>';}

function incidentForm(PDO $db,array $vehicles,array $people,array $materials,?array $incident=null):void{
 $isEdit=$incident!==null;$assignedVehicles=[];$assignedCrew=[];$assignedMaterials=[];$assignedByPerson=[];
 foreach($people as $p)$assignedByPerson[(int)$p['id']]=(int)($p['vehicle_id']??0);
 if($isEdit){$q=$db->prepare('SELECT vehicle_id FROM incident_vehicles WHERE incident_id=?');$q->execute([(int)$incident['id']]);$assignedVehicles=array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN));$q=$db->prepare('SELECT vehicle_id,personnel_id FROM incident_personnel WHERE incident_id=?');$q->execute([(int)$incident['id']]);foreach($q->fetchAll(PDO::FETCH_ASSOC) as $row)$assignedCrew[(int)$row['vehicle_id']][]=(int)$row['personnel_id'];$q=$db->prepare('SELECT material_id FROM incident_materials WHERE incident_id=?');$q->execute([(int)$incident['id']]);$assignedMaterials=array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN));}
 $val=fn(string $key,string $default='')=>h($incident[$key]??$default);
 echo '<div class="card"><h1>'.($isEdit?'Einsatz bearbeiten':'Neuer Einsatz').'</h1><form method="post"><input type="hidden" name="form" value="incident">'.($isEdit?'<input type="hidden" name="incident_id" value="'.(int)$incident['id'].'">':'');
 echo '<label>Einsatznummer</label><input name="incident_number" value="'.$val('incident_number').'" placeholder="z. B. 2026-123"><label>Einsatz / Stichwort</label><input name="title" required value="'.$val('title').'" placeholder="z. B. Ölspur"><label>Einsatzort</label><input name="location" required value="'.$val('location').'" placeholder="z. B. Halchterstr. 2"><div class="grid"><div><label>Datum</label><input type="date" name="incident_date" value="'.$val('incident_date',date('Y-m-d')).'" required></div><div><label>Beginn <span class="muted">(Ende der kostenlosen gesetzlichen Hilfe)</span></label><input type="time" name="start_time" value="'.$val('start_time').'"></div><div><label>Ende</label><input type="time" name="end_time" value="'.$val('end_time').'"></div></div>';
 echo '<div class="grid"><div><label>Einsatzleiter</label><input name="incident_leader" value="'.$val('incident_leader').'" placeholder="Name des Einsatzleiters"></div><div><label>Dokument ausgefüllt von</label><input name="document_filled_by" value="'.$val('document_filled_by').'" placeholder="Name"></div></div>';
 echo '<h2>Fahrzeuge und Besatzung</h2>';foreach($vehicles as $v){$vid=(int)$v['id'];$checked=in_array($vid,$assignedVehicles,true);echo '<div class="crew"><label class="check"><input type="checkbox" name="vehicles[]" value="'.$vid.'" '.($checked?'checked':'').' onchange="this.closest(\'.crew\').querySelector(\'.crewlist\').hidden=!this.checked"> 🚒 '.h($v['name']).' <span class="muted">'.h($v['call_sign']).'</span></label><div class="crewlist" '.($checked?'':'hidden').'>';if(!$people)echo '<span class="muted">Noch kein Personal angelegt.</span>';foreach($people as $p){$pid=(int)$p['id'];$masterVehicle=(int)($p['vehicle_id']??0);$pc=in_array($pid,$assignedCrew[$vid]??[],true);$allowed=$masterVehicle===0||$masterVehicle===$vid||$pc;$disabled=$allowed?'':'disabled';echo '<label class="check" title="'.($allowed?'':'In den Stammdaten Fahrzeug '.h((string)$masterVehicle).' zugeordnet').'" style="'.($allowed?'':'opacity:.4').' "><input type="checkbox" name="crew['.$vid.'][]" value="'.$pid.'" '.$disabled.' '.($pc?'checked':'').'> '.h($p['name']).'</label>';}echo '</div></div>';}
 echo '<h2>Material</h2>';if($materials){echo '<div class="material-list">';foreach($materials as $m){$mc=in_array((int)$m['id'],$assignedMaterials,true);echo '<label><input type="checkbox" name="materials[]" value="'.$m['id'].'" '.($mc?'checked':'').'> '.h($m['name']).'</label>';}echo '</div>';}else echo '<p class="muted">Noch kein Material in den Stammdaten angelegt.</p>';
 echo '<label>Sonstiges Material (Freitext)</label><textarea name="material" rows="3" placeholder="z. B. zusätzlich 2x Ölbindemittel">'.$val('material').'</textarea><label>Bemerkungen</label><textarea name="notes" rows="4">'.$val('notes').'</textarea>';
 echo '<h2>Verursacher</h2><div class="grid"><div class="person-block"><h3>Verursacher 1</h3><label>Name</label><input name="culprit1_name" value="'.$val('culprit1_name').'" placeholder="Name"><label>Geburtsdatum</label><input type="date" name="culprit1_birthdate" value="'.$val('culprit1_birthdate').'"></div><div class="person-block"><h3>Verursacher 2</h3><label>Name</label><input name="culprit2_name" value="'.$val('culprit2_name').'" placeholder="Name"><label>Geburtsdatum</label><input type="date" name="culprit2_birthdate" value="'.$val('culprit2_birthdate').'"></div><div class="person-block"><h3>Unklar</h3><label>Name</label><input name="culprit_unknown_name" value="'.$val('culprit_unknown_name').'" placeholder="Name"><label>Geburtsdatum</label><input type="date" name="culprit_unknown_birthdate" value="'.$val('culprit_unknown_birthdate').'"></div></div>';
 echo '<br><div class="actions"><button type="submit">'.($isEdit?'Änderungen speichern':'Einsatz speichern').'</button>'.($isEdit?'<a class="btn danger" href="?action=view&id='.(int)$incident['id'].'">Abbrechen</a>':'').'</div></form></div>';
}

headerHtml();
if($action==='new'){incidentForm($db,$vehicles,$people,$materials);}
elseif($action==='edit'){$s=$db->prepare('SELECT * FROM incidents WHERE id=?');$s->execute([$editId]);$incident=$s->fetch(PDO::FETCH_ASSOC);if(!$incident)echo '<div class="card"><h1>Einsatz nicht gefunden</h1></div>';else incidentForm($db,$vehicles,$people,$materials,$incident);}
elseif($action==='master'){
 echo '<div class="card"><h1>Stammdaten</h1><p class="muted">Personal kann genau einem Stammfahrzeug zugeordnet werden. Ist eine Person Fahrzeug A zugeordnet, ist sie bei Fahrzeug B ausgegraut.</p></div>';
 echo '<div class="master-grid">';
 echo '<div class="card"><h2>👨‍🚒 Personal</h2><form method="post"><input type="hidden" name="form" value="person"><div class="inline"><div><label>Name</label><input name="name" required></div><div><label>Funktion</label><input name="function" placeholder="z. B. Maschinist"></div></div><label>Stammfahrzeug</label><select name="vehicle_id"><option value="0">— keinem Fahrzeug fest zugeordnet —</option>';foreach($vehicles as $v)echo '<option value="'.$v['id'].'">'.h($v['name']).' · '.h($v['call_sign']).'</option>';echo '</select><br><button>Person anlegen</button></form><hr>';
 foreach($people as $p){echo '<div class="master-row"><form method="post"><input type="hidden" name="form" value="person"><input type="hidden" name="id" value="'.$p['id'].'"><div class="inline"><div><label>Name</label><input name="name" value="'.h($p['name']).'" required></div><div><label>Funktion</label><input name="function" value="'.h($p['function']).'"></div></div><label>Stammfahrzeug</label><select name="vehicle_id"><option value="0">— kein Fahrzeug —</option>';foreach($vehicles as $v)echo '<option value="'.$v['id'].'" '.((int)($p['vehicle_id']??0)===(int)$v['id']?'selected':'').'>'.h($v['name']).'</option>';echo '</select><br><button>💾 Speichern</button></form></div>';}
 echo '</div>';
 echo '<div class="card"><h2>🚒 Fahrzeuge</h2><form method="post"><input type="hidden" name="form" value="vehicle"><div class="grid"><div><label>Bezeichnung</label><input name="name" required placeholder="LF 8"></div><div><label>Funkrufname</label><input name="call_sign"></div></div><br><button>Fahrzeug anlegen</button></form><hr>';
 foreach($vehicles as $v){echo '<div class="master-row"><form method="post"><input type="hidden" name="form" value="vehicle"><input type="hidden" name="id" value="'.$v['id'].'"><div class="grid"><div><label>Bezeichnung</label><input name="name" value="'.h($v['name']).'" required></div><div><label>Funkrufname</label><input name="call_sign" value="'.h($v['call_sign']).'"></div></div><br><button>💾 Speichern</button></form></div>';}echo '</div>';
 echo '<div class="card"><h2>🧰 Material</h2><form method="post"><input type="hidden" name="form" value="material"><label>Bezeichnung</label><input name="name" required placeholder="z. B. Ölbindemittel"><br><button>Material anlegen</button></form><hr>';
 foreach($materials as $m){echo '<div class="master-row"><form method="post"><input type="hidden" name="form" value="material"><input type="hidden" name="id" value="'.$m['id'].'"><div class="inline"><div><label>Bezeichnung</label><input name="name" value="'.h($m['name']).'" required></div><div><br><button>💾 Speichern</button></div></div></form></div>';}echo '</div></div>';
}
elseif($action==='view'){$id=$editId;$s=$db->prepare('SELECT * FROM incidents WHERE id=?');$s->execute([$id]);$i=$s->fetch(PDO::FETCH_ASSOC);if(!$i)echo '<div class="card"><h1>Einsatz nicht gefunden</h1></div>';else{$sv=$db->prepare('SELECT v.* FROM vehicles v JOIN incident_vehicles iv ON iv.vehicle_id=v.id WHERE iv.incident_id=? ORDER BY v.name');$sv->execute([$id]);$used=$sv->fetchAll(PDO::FETCH_ASSOC);echo '<div class="card"><div class="actions"><a class="btn" href="?action=edit&id='.$id.'">✏️ Einsatz bearbeiten</a><a class="btn danger" href="?">← Zur Übersicht</a></div><h1>'.($i['incident_number']?'<span class="muted">#'.h($i['incident_number']).'</span> ':'').h($i['title']).'</h1><p><strong>📍 '.h($i['location']).'</strong><br>📅 '.h($i['incident_date']).'<br>🕐 Beginn: '.h($i['start_time']).'<br>🕐 Ende: '.h($i['end_time']).'<br>👨‍🚒 Einsatzleiter: '.h($i['incident_leader']).'<br>📝 Dokument ausgefüllt von: '.h($i['document_filled_by']).'</p><h2>Fahrzeuge & Besatzung</h2>';foreach($used as $v){echo '<div class="crew"><strong>🚒 '.h($v['name']).'</strong><br>';$sp=$db->prepare('SELECT p.name FROM personnel p JOIN incident_personnel ip ON ip.personnel_id=p.id WHERE ip.incident_id=? AND ip.vehicle_id=? ORDER BY p.name');$sp->execute([$id,$v['id']]);$pp=$sp->fetchAll(PDO::FETCH_ASSOC);echo $pp?implode(' · ',array_map(fn($p)=>h($p['name']),$pp)):'Keine Besatzung erfasst';echo '</div>';}$sm=$db->prepare('SELECT m.name FROM materials m JOIN incident_materials im ON im.material_id=m.id WHERE im.incident_id=? ORDER BY m.name');$sm->execute([$id]);$usedMaterials=$sm->fetchAll(PDO::FETCH_COLUMN);echo '<h2>Material</h2>';if($usedMaterials)echo '<p>'.implode(' · ',array_map('h',$usedMaterials)).'</p>';if(trim($i['material'])!=='')echo '<p>'.nl2br(h($i['material'])).'</p>';if(!$usedMaterials&&trim($i['material'])==='')echo '<p class="muted">Kein Material erfasst.</p>';echo '<h2>Verursacher</h2><div class="grid">';$culprits=[['Verursacher 1',$i['culprit1_name'],$i['culprit1_birthdate']],['Verursacher 2',$i['culprit2_name'],$i['culprit2_birthdate']],['Unklar',$i['culprit_unknown_name'],$i['culprit_unknown_birthdate']]];foreach($culprits as $c){echo '<div class="person-block"><h3>'.h($c[0]).'</h3><p><strong>Name:</strong> '.($c[1]!==''?h($c[1]):'<span class="muted">Nicht erfasst</span>').'<br><strong>Geburtsdatum:</strong> '.($c[2]!==''?h($c[2]):'<span class="muted">Nicht erfasst</span>').'</p></div>';}echo '</div><h2>Bemerkungen</h2><p>'.nl2br(h($i['notes'])).'</p></div>';}}
else{$items=$db->query('SELECT * FROM incidents ORDER BY incident_date DESC,id DESC')->fetchAll(PDO::FETCH_ASSOC);echo '<div class="card"><h1>Einsätze</h1><a class="btn" href="?action=new">+ Neuer Einsatz</a></div>';if(!$items)echo '<div class="card"><p>Noch keine Einsätze angelegt.</p></div>';foreach($items as $i)echo '<div class="card"><h2><a href="?action=view&id='.$i['id'].'">'.($i['incident_number']?'<span class="muted">#'.h($i['incident_number']).'</span> ':'').h($i['title']).'</a></h2><p>📍 '.h($i['location']).' · '.h($i['incident_date']).' · '.h($i['start_time']).' – '.h($i['end_time']).'</p><a class="btn danger" href="?action=edit&id='.$i['id'].'">✏️ Bearbeiten</a></div>';}
footerHtml();
